##### FUNDAMENTALS -
#### • Computer Science 
### • Programming concepts
## • Internet and web 

## Foundations of Computing and Programming

### Computer Basics and Data Representation
- A **computer** can be abstracted as a **Turing machine**, capable of computing anything by reading and writing a tape of bits (ones and zeros).
- The **CPU** (Central Processing Unit) is the brain of the computer, containing billions of **transistors** acting as microscopic on/off switches.
- The smallest unit of data is a **bit**; 8 bits form a **byte**, which can represent 256 values (e.g., characters in ASCII or UTF-8 encoding).
- Humans find binary hard to read, so it’s often represented in **hexadecimal** (base 16), where each 4-bit group is a **nibble**.
- **Machine code** is the binary code directly executed by the CPU, generated by compiling or interpreting high-level programming languages.

### Memory and Hardware Interaction
- **RAM** (Random Access Memory) stores data temporarily, organized by **memory addresses** accessible by the CPU.
- Input/output devices (keyboard, mouse, monitor) allow interaction with the computer.
- **Operating systems** (e.g., Linux, Windows, Mac) manage hardware resources through **kernels** and **device drivers**.
- The **shell** provides a command line interface to interact with the OS, including remote access via **SSH** (Secure Shell).

---

## Programming Languages and Execution Models

### Language Types and Execution
- Programming languages abstract hardware complexity for humans.
- **Interpreted languages** (e.g., Python) run code line-by-line via an interpreter.
- **Compiled languages** (e.g., C++) translate the entire program into machine code ahead of time, producing executables.

### Variables, Types, and Memory Management
- Variables bind names to data stored in memory.
- Languages can be **dynamically typed** (Python: type inferred at runtime) or **statically typed** (C: types declared explicitly).
- **Pointers** hold memory addresses, enabling low-level memory control.
- **Garbage collection** automates memory allocation and deallocation, reducing manual memory management.

### Common Data Types
| Data Type      | Description                                  | Example/Use                      |
|----------------|----------------------------------------------|---------------------------------|
| `int`          | Whole numbers, signed or unsigned             | Counting items                  |
| `float`        | Decimal numbers with limited precision        | Scientific calculations         |
| `double`       | Higher precision floating-point numbers       | More accurate computations      |
| `char`         | Single character                               | Storing letters or symbols      |
| `string`       | Sequence of characters                         | Text manipulation               |
| **Endianness** | Byte order in memory: **big endian** (most significant byte first) vs **little endian** (least significant byte first) | Affects data interpretation     |

---

## Data Structures and Algorithms

### Essential Data Structures
- **Array/List**: Ordered collection accessed by integer indices starting at zero.
- **Linked List**: Items linked via pointers to the next element.
- **Stack**: Last-In-First-Out (LIFO), like a stack of plates.
- **Queue**: First-In-First-Out (FIFO), like a line at a store.
- **Hash/Map/Dictionary**: Key-value pairs, enabling fast lookup by keys.
- **Tree**: Hierarchical structure with nodes, useful for faster traversal.
- **Graph**: Nodes connected by edges, representing complex relationships.

### Algorithms and Code Structure
- An **algorithm** is a set of instructions solving a problem.
- **Functions** encapsulate code blocks, take inputs (arguments), and return outputs.
- **Expressions** produce values (e.g., boolean comparisons), while **statements** perform actions (e.g., if, loops).
- **Conditional logic** uses `if-else` to execute code based on boolean conditions.
- **Loops** (for, while) repeat code blocks; for loops iterate over arrays or iterables.
- **Recursion**: A function calling itself; requires a **base case** to avoid infinite loops and stack overflow.

### Algorithm Efficiency
- **Big-O notation** measures algorithm performance by time and space complexity.
- Algorithm types:
  - **Brute force:** Exhaustive search.
  - **Divide and conquer:** Break problem in halves (e.g., binary search).
  - **Dynamic programming:** Store results of subproblems (**memoization**) to avoid recomputation.
  - **Greedy algorithms:** Make the best immediate choice (e.g., Dijkstra’s shortest path).
  - **Backtracking:** Explore all options incrementally (e.g., maze solving).

---

## Programming Paradigms and Advanced Concepts

### Paradigms
- **Declarative programming:** Describes *what* to do, abstracting control flow (e.g., functional languages like Haskell).
- **Imperative programming:** Specifies *how* to perform tasks explicitly (e.g., procedural languages like C).
- Most modern languages (Python, JavaScript, Kotlin, Swift) are **multi-paradigm**, supporting multiple styles.

### Object-Oriented Programming (OOP)
- Uses **classes** as blueprints encapsulating **properties** (variables) and **methods** (functions).
- **Inheritance** allows subclasses to extend or override parent class behavior.
- Objects created from classes live in **heap memory**, enabling references by multiple variables without duplicating data.
- The **call stack** manages function execution context; recursion and function calls push frames onto the stack.

### Concurrency and Parallelism
- CPUs have multiple **threads** (virtual cores) enabling parallel execution.
- Some languages support **parallelism** (running code simultaneously on different threads).
- **Concurrency models** (event loops, coroutines) allow multitasking on a single thread by pausing and resuming tasks.

---

## Networking and Modern Computing

### Virtualization and Networking
- **Virtual Machines (VMs)** simulate hardware, allowing a single physical machine to run multiple virtual computers.
- VMs form the backbone of cloud computing.
- Each machine has an **IP address** and often a **URL** mapped via the **Domain Name Service (DNS)**.
- Communication uses protocols:
  - **TCP handshake** for reliable connection setup.
  - **SSL/TLS** for encryption.
  - **HTTP** for web communication.
- Servers expose data through **APIs**, commonly using **REST** architecture mapping URLs to data entities.

---

## Practical Realities

- Despite the complexity, software engineering allows people to build powerful programs without deep understanding of underlying hardware.
- Debugging often starts with doing nothing and rerunning code before more complex investigation.
- Managing printers and other peripherals remains a practical skill for programmers, reinforcing the importance of understanding hardware interaction.

---

### Summary & Key Takeaways
- Computers operate on bits and bytes, controlled by CPUs and memory, abstracted by operating systems and programming languages.
- Programming languages convert human-friendly code into machine code, with varied typing and execution models.
- Data structures and algorithms are essential tools for organizing and processing data efficiently.
- Understanding paradigms (declarative, imperative, OOP) helps write clearer, reusable, and scalable code.
- Modern computing relies on virtualization, networking protocols, and secure communication to power the internet.
- Practical software engineering balances deep technical knowledge with abstractions that make coding accessible and productive.
- Algorithms must be evaluated on efficiency using Big-O notation to ensure scalability.
- Concurrency and parallelism improve program performance on modern multi-core CPUs.
- Mastery of these concepts enables building reliable, efficient, and secure software systems.
